import { test } from "node:test";
import { expectAllow, expectDeny } from "../../test/harness.ts";

const denied: Record<string, readonly string[]> = {
	"git-reset-hard": [
		// Global options before the subcommand.
		"git -C repo reset --hard",
		"git -Crepo reset --hard",
		"git -C repo -C sub reset --hard",
		"git -c core.x=y reset --hard",
		"git -c core.x=y -c a.b=c reset --hard",
		"git --git-dir=.git reset --hard",
		"git --git-dir .git reset --hard",
		"git --git-dir .git --work-tree . reset --hard",
		"git --work-tree=. reset --hard",
		"git --no-pager reset --hard",
		"git -p reset --hard",
		"git -P reset --hard",
		"git --paginate reset --hard",
		"git --namespace=x reset --hard",
		"git --namespace x reset --hard",
		"git --exec-path=/x reset --hard",
		"git --bare reset --hard",
		"git --literal-pathspecs reset --hard",
		"git --no-optional-locks reset --hard",
		"git --config-env=a.b=ENV reset --hard",
		"git --config-env a.b=ENV reset --hard",
		"git --attr-source HEAD reset --hard",
		"git --made-up reset --hard",
		"/usr/bin/git reset --hard",
		"env GIT_DIR=.git git reset --hard",
		"GIT_DIR=.git git reset --hard",
		// The rule itself.
		"git reset --hard",
		"git reset --hard HEAD~1",
		"git reset --hard origin/main",
		"git reset -q --hard",
		"git reset --hard -q",
		"git reset --har",
		"git reset --ha",
		// git 2.55.0 resolves `--h` to `--hard` and discards changes.
		"git reset --h",
		"ls && git reset --hard",
		"bash -c 'git reset --hard'",
		"echo $(git reset --hard)",
	],
	"git-clean": [
		"git clean -f",
		"git clean -fd",
		"git clean -df",
		"git clean -fdx",
		"git clean -xdf",
		"git clean -ffdx",
		"git clean -f -d -x",
		"git clean --force",
		"git clean --forc",
		"git clean -f -- src",
		"git clean -d",
		"git clean",
		"git clean -i",
		"git clean --interactive",
		"git -c clean.requireForce=false clean -d",
		"git clean -e keep -f",
		// -n is the value of -e here, so not a dry run.
		"git clean -f -e -n",
		"git clean -f --exclude -n",
		"git clean -f -- -n",
	],
	"git-checkout-discard": [
		"git checkout -- file.txt",
		"git checkout -- .",
		"git checkout HEAD -- file.txt",
		"git checkout main -- src/",
		"git checkout .",
		"git checkout ./",
		"git checkout :/",
		"git checkout :/:",
		"git checkout '*'",
		"git checkout ':(top)src'",
		"git checkout HEAD .",
		"git checkout -f",
		"git checkout -f main",
		"git checkout -fq main",
		"git checkout --force main",
		"git checkout --forc main",
		"git checkout --ours .",
		"git checkout --theirs -- file.txt",
		"git checkout --pathspec-from-file=list.txt",
		"git checkout --pathspec-from-file list.txt",
		"git switch -f main",
		"git switch --force main",
		"git switch --discard-changes main",
		"git switch --discard main",
	],
	"git-restore-worktree": [
		"git restore file.txt",
		"git restore .",
		"git restore -W file.txt",
		"git restore --worktree file.txt",
		"git restore --work file.txt",
		"git restore -SW file.txt",
		"git restore -WS file.txt",
		"git restore -S -W file.txt",
		"git restore --staged --worktree file.txt",
		"git restore --source=HEAD~1 file.txt",
		"git restore -s HEAD~1 file.txt",
		"git restore -p file.txt",
		// Allow-flags match exactly: --stage is not --staged.
		"git restore --stage file.txt",
	],
	"git-stash-destroy": [
		"git stash drop",
		"git stash drop stash@{1}",
		"git stash drop -q stash@{0}",
		"git stash clear",
		"git stash -q drop",
		"git -C repo stash clear",
	],
};

const allowed = [
	"git status",
	'git log --grep "reset --hard"',
	'git commit -m "git reset --hard fixed it"',
	"git reset",
	"git reset HEAD file.txt",
	"git reset --soft HEAD~1",
	"git reset --mixed HEAD~1",
	"git reset --keep HEAD~1",
	"git reset --merge",
	"git reset -- --hard",
	"git -C reset status",
	"git clean -n",
	"git clean -nd",
	"git clean -dn",
	"git clean -fn",
	"git clean -n -f",
	"git clean --dry-run -f",
	"git clean -fd --dry-run",
	"git checkout main",
	"git checkout -b feature",
	"git checkout -B feature",
	// Real git: `--` is -b's branch name here, not the pathspec separator.
	"git checkout -b -- feature",
	"git checkout --orphan gh-pages",
	"git checkout feature/x",
	"git checkout -",
	"git checkout -p",
	"git switch main",
	"git switch -c feature",
	"git switch -",
	"git restore --staged file.txt",
	"git restore -S file.txt",
	"git restore --staged .",
	"git restore -s HEAD --staged file.txt",
	"git restore -sW --staged file.txt",
	"git stash",
	"git stash list",
	"git stash show -p",
	"git stash pop",
	"git stash apply stash@{1}",
	"git stash push -m wip",
	"git stash push -m drop",
	"git stash branch tmp",
	"git branch -D feature",
	"git branch --delete --force feature",
	"git branch -d feature",
	"git help reset",
	"git --version",
	"echo git reset --hard",
];

const acceptedMisses: readonly (readonly [string, string])[] = [
	["git checkout file.txt", "a path without -- looks like a branch"],
	["git checkout src/", "a path without -- looks like a branch"],
	["git checkout-index -a -f", "checkout-index"],
	["git config alias.nuke 'reset --hard'", "git aliases"],
	["git -c alias.nuke='!rm -rf x' nuke", "git aliases"],
];

for (const [rule, commands] of Object.entries(denied)) {
	for (const command of commands) {
		test(`deny ${rule}: ${command}`, () => expectDeny(command, rule));
	}
}

for (const command of allowed) {
	test(`allow: ${command}`, () => expectAllow(command));
}

for (const [command, why] of acceptedMisses) {
	test(`allow (accepted miss: ${why}): ${command}`, () => expectAllow(command));
}
